.TH BITLOCKER-MOUNT 1 "2026" "BitLocker macOS FUSE Driver"
.SH NAME
bitlocker-mount \- mount BitLocker volumes using macFUSE
.SH SYNOPSIS
.B bitlocker-mount
.I <volume>
.I <mountpoint>
.SH DESCRIPTION
Mounts a BitLocker-encrypted volume on macOS using macFUSE and the internal BitLocker crypto engine.
