.TH BITLOCKER-DECRYPT 1 "2026" "BitLocker macOS FUSE Driver"
.SH NAME
bitlocker-decrypt \- export decrypted files from a BitLocker volume
.SH SYNOPSIS
.B bitlocker-decrypt
.I <volume>
.I <output-directory>
.SH DESCRIPTION
Decrypts the specified BitLocker volume and writes decrypted contents to the target output directory.
